import Head from "next/head";
import React from "react";
import Image from "next/image";

export default function Home({ }) {
  return (
    <div>
      <Head>
        <title>Smart Identities</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <script async data-api="/_hive" src="/bee.js"></script>
        <script async src="https://tally.so/widgets/embed.js"></script>
      </Head>


      <nav className="text-gray-100 py-6 px-10">
        identities
      </nav>
      <main className="flex flex-col items-center justify-center h-[90vh] gap-5">
        <h1 className="font-extrabold text-5xl text-white text-center">Form <span className="text-[#03D9FC]">decentralised</span> and <br /><span className="text-[#03D9FC]">disposable identities</span> on-chain</h1>
        <p className="text-[#7D7D7D] font-medium text-lg text-center">Join together with your partners to act as a single identity<br />while spliting returns with equitites.</p>
        <a data-splitbee-event="clicked on cta" href="https://tally.so#tally-open=3EkaJB&tally-layout=modal&tally-width=400&tally-hide-title=1" className="z-10 mt-10 bg-gradient-to-r to-[#00E0FF] from-[#1988D8] flex text-[#002D63] font-semibold gap-2 px-3 pr-4 py-2 rounded">
          <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
            <path strokeLinecap="round" strokeLinejoin="round" d="M13 7l5 5m0 0l-5 5m5-5H6" />
          </svg>
          GET ACCESS
        </a>
      </main>
      <Image className="-z-50" src="/image/bg.png" layout="fill" />
    </div>
  );
}
