name: npm audit

on:
  pull_request:
  push:
    branches:
      - master
      - "releases/*"
                      
jobs:
  build:
    name: npm audit (frontend)
    runs-on: ubuntu-latest
    defaults: 
      run:
        working-directory: ./frontend
        
    steps:
      - name : Clone Repo
        uses: actions/checkout@v2
      
      - name: Go to frontend & Install Dependencies
        run: npm install --legacy-peer-deps
      
      - name: Audit and PR fixes
        uses: luisfontes19/npm-audit-action@v0.1.0
        with:
          fix: true
          git-user: 0xSJ Clone
          git-email: robot@sudham.tk
          github-token: ${{ secrets.GH_TOKEN }}
