name: npm audit

on:
  pull_request:
  push:
    branches:
      - master
      - "releases/*"

jobs:
  build:
    name: Audit
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          
      - name: Go to frontend
        run: cd frontend
        
      - name: Install Dependencies
        run: npm install --legacy-peer-deps
      
      - name: Audit and fix
        uses: luisfontes19/npm-audit-action@v0.1.0
        with:
          fix: true
          github-token: ${{ secrets.GITHUB_TOKEN }}   
          
