name: npm audit

on:
  pull_request:
  push:
    branches:
      - master
      - "releases/*"
  schedule:
    - cron: "0 10 * * *"

jobs:
  scan:
    name: npm audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: cd frontend && npm install  --legacy-peer-deps
      - uses: oke-py/npm-audit-action@v2
        with:
          audit_level: moderate
          github_token: ${{ secrets.GITHUB_TOKEN }}
          issue_assignees: sudhamjayanthi
          issue_labels: audit
          dedupe_issues: true
          working_directory: frontend
