name: npm audit

on:
  pull_request:
  push:
    branches:
      - master
      - "releases/*"
                      
jobs:
  build:
    name: npm audit
    runs-on: ubuntu-latest

    steps:
      - name : Checkout
        uses: actions/checkout@v2
      
      - name: Install Dependencies
        run: cd frontend && npm install --legacy-peer-deps
      
      - name: Audit and PR fixes
        uses: luisfontes19/npm-audit-action@v0.1.0
        with:
          fix: true
          level: moderate
          git-user: 0xSJ Clone
          git-email: robot@sudham.tk
          github-token: ${{ secrets.GH_TOKEN }}
